workflows:
  ios_testflight:
    name: iOS → TestFlight (auto-signing)
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - Apple               # uses your APPSTORE_* env vars you added in Codemagic UI
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        APP_VERSION: 1.0.0

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Fetch signing files from App Store Connect
        script: |
          set -e
          # Load any uploaded certs (optional, safe if none)
          keychain add-certificates

          # Ask App Store Connect (via your APPSTORE_* vars) to fetch or CREATE
          # an iOS App Store provisioning profile that matches your bundle id.
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --platform IOS \
            --create

          # Attach the fetched profile(s) to the Xcode project
          xcode-project use-profiles

      - name: Set app versions
        script: |
          # Marketing version (optional)
          if [ -n "$APP_VERSION" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
          fi
          # Unique build number from Codemagic build id
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CM_BUILD_ID" ios/Runner/Info.plist || true

      - name: Create export options (App Store)
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF

      - name: Build signed IPA (Release)
        script: |
          flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        # Uses your environment variables (Settings → Environment variables → group "Apple")
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        api_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true
