# ---------- TOP-LEVEL CODE SIGNING (not inside a workflow) ----------
code_signing:
  ios_signing:
    certificates:
      - certificate: MindBreathDistribution       # EXACT name from Teams → iOS certificates
        password: $P12_PASSWORD                   # add this as a Secret in Env variables UI
    provisioning_profiles:
      - MB_AppStore_Profile                       # EXACT name from Teams → iOS provisioning profiles

# -------------------- WORKFLOWS --------------------
workflows:
  ios_manual_sign:
    name: iOS Manual Sign & IPA
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        # Do NOT put the actual password here; only reference $P12_PASSWORD above.

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Apply signing assets (keychain + profiles)
        script: |
          keychain add-certificates
          xcode-project use-profiles

      - name: Create export options for App Store
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.carlostechops.mindbreath</key><string>MB_AppStore_Profile</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      - name: Build signed IPA (Release)
        script: flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
