workflows:
  android_aab:
    name: MindBreath Android → AAB artifact
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build Android App Bundle (release)
        script: |
          flutter build appbundle --release
      - name: List artifacts
        script: |
          echo "AAB at: build/app/outputs/bundle/release/app-release.aab"
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
