workflows:
  ios_testflight:
    name: iOS → TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - Apple            # loads your P12/Provisioning/App Store Connect vars
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        APP_VERSION: 1.0.2

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Install certificate & provisioning profile from env
        script: |
          set -euo pipefail

          KEYCHAIN_PATH="$HOME/Library/Keychains/build.keychain-db"
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"

          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"

          echo "$P12_BASE64" | base64 --decode > cert.p12
          security import cert.p12 -k "$KEYCHAIN_PATH" -P "$P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security find-identity -v -p codesigning "$KEYCHAIN_PATH" || true

          mkdir -p "$PROFILES_DIR"
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > "$PROFILES_DIR/MB_AppStore_Profile.mobileprovision"

      - name: Apply provisioning profiles (Codemagic CLI)
        script: |
          set -euo pipefail
          # Map the installed .mobileprovision to the Xcode targets
          xcode-project use-profiles \
            --project ios/Runner.xcodeproj \
            --targets "Runner"

          # Pods target often doesn’t need signing; ignore if it isn’t present
          xcode-project use-profiles \
            --project ios/Pods/Pods.xcodeproj \
            --targets "Pods-Runner" || true

          # Show what got applied
          xcode-project show-build-settings --project ios/Runner.xcodeproj --targets "Runner" | grep -E "DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_STYLE" || true
      - name: Create export options (App Store)
        script: |
          set -euo pipefail
          printf '%s' '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.carlostechops.mindbreath</key><string>MB_AppStore_Profile</string>
            </dict>
            <key>destination</key><string>export</string>
          </dict></plist>' > export_options.plist

      - name: Set marketing version & bump build number
        script: |
          set -euo pipefail
          if [ -n "${APP_VERSION:-}" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
          fi
          BUILD_NUM=${CM_BUILD_ID##*-}
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" ios/Runner/Info.plist || true

            - name: Build signed IPA (Release)
              script: |
                set -euo pipefail
                BUILD_NUM=${CM_BUILD_ID##*-}
                # sanity: reflect what we plan to build
                /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
                /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/Runner/Info.plist || true
                echo "Version about to build: $APP_VERSION ($BUILD_NUM)"
                flutter build ipa \
                  --release \
                  --build-name="$APP_VERSION" \
                  --build-number="$BUILD_NUM" \
                  --export-options-plist=export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        api_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true

  android_release:
    name: Android Release (.aab)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - Apple        # you placed ANDROID_* secrets in this group
      vars:
        MB_BUILD_NAME: "1.0.2"

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Configure Android signing (auto-detect)
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          echo "🔎 Detecting keystore source…"

          have_custom=false
          have_cm=false

          [[ -n "${ANDROID_KEYSTORE_BASE64:-}" && -n "${ANDROID_KEY_ALIAS:-}" ]] && have_custom=true
          [[ -n "${CM_KEYSTORE_PATH:-}"   && -n "${CM_KEY_ALIAS:-}"   ]] && have_cm=true

          if $have_custom; then
            echo "✅ Using custom ANDROID_* secrets"
            : "${ANDROID_KEYSTORE_PASSWORD:?missing ANDROID_KEYSTORE_PASSWORD}"
            : "${ANDROID_KEY_PASSWORD:?missing ANDROID_KEY_PASSWORD}"

            # Decode keystore (strip whitespace just in case)
            echo "${ANDROID_KEYSTORE_BASE64}" | tr -d '\n\r ' | base64 --decode > /tmp/keystore.jks

            # Sanity-check + alias
            keytool -list -keystore /tmp/keystore.jks -storepass "$ANDROID_KEYSTORE_PASSWORD" >/tmp/ks.txt 2>/dev/null \
              || { echo "❌ Wrong ANDROID_KEYSTORE_PASSWORD"; exit 1; }
            grep -q "Alias name: ${ANDROID_KEY_ALIAS}$" /tmp/ks.txt \
              || { echo "❌ Alias '${ANDROID_KEY_ALIAS}' not found in keystore"; cat /tmp/ks.txt; exit 1; }

            # Write key.properties via printf (avoids heredoc issues)
            printf "storeFile=/tmp/keystore.jks\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\nstoreType=jks\n" \
              "$ANDROID_KEYSTORE_PASSWORD" "$ANDROID_KEY_ALIAS" "$ANDROID_KEY_PASSWORD" \
              > android/app/key.properties

          elif $have_cm; then
            echo "✅ Using Codemagic keystore (CM_KEYSTORE_*)"
            : "${CM_KEYSTORE_PASSWORD:?missing}"
            : "${CM_KEY_ALIAS:?missing}"
            : "${CM_KEY_PASSWORD:?missing}"

            keytool -list -keystore "$CM_KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" >/tmp/ks.txt 2>/dev/null \
              || { echo "❌ Wrong CM_KEYSTORE_PASSWORD"; exit 1; }
            grep -q "Alias name: ${CM_KEY_ALIAS}$" /tmp/ks.txt \
              || { echo "❌ Alias '${CM_KEY_ALIAS}' not found in keystore"; cat /tmp/ks.txt; exit 1; }

            printf "storeFile=%s\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\nstoreType=jks\n" \
              "$CM_KEYSTORE_PATH" "$CM_KEYSTORE_PASSWORD" "$CM_KEY_ALIAS" "$CM_KEY_PASSWORD" \
              > android/app/key.properties

          else
            echo "❌ No signing creds found."
            echo "Provide either ANDROID_* secrets (group) OR select a keystore in Distribution so CM_KEYSTORE_* exist."
            exit 1
          fi

          echo "📄 key.properties summary:"
          grep -E '^(storeFile|keyAlias)=' android/app/key.properties || true

      - name: Build release AAB
        script: |
          set -euo pipefail
          flutter build appbundle \
            --release \
            --build-name="$MB_BUILD_NAME" \
            --build-number="$BUILD_NUMBER"

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
