workflows:
  android_aab:
    name: MindBreath Android → AAB artifact
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build Android App Bundle (release)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

  ios_adhoc_sign:
    name: iOS Ad Hoc – signed IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X

    scripts:
      - name: Get dependencies
        script: flutter pub get

      # ⬇️ THIS step now forces manual signing and then applies the uploaded profiles/cert
      - name: Add signing assets & select profiles
        script: |
          keychain add-certificates
          # Force Manual signing for all targets/configs in the Xcode project
          xcode-project build-settings set CODE_SIGN_STYLE=Manual
          # Show for verification (non-fatal if it can't print)
          xcode-project build-settings print CODE_SIGN_STYLE || true
          # Apply the uploaded provisioning profiles/certificates
          xcode-project use-profiles

      # ⬇️ Optional “belt-and-suspenders” to make sure automatic signing is OFF
      - name: Extra safety: disable automatic signing
        script: |
          xcode-project automatic-signing disable

      - name: Create export options for Ad Hoc
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>ad-hoc</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.carlostechops.mindbreath</key><string>MB_AdHoc_Profile</string>
            </dict>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      - name: Build signed IPA (Release)
        script: flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
