workflows:
  android_aab:
    name: MindBreath Android → AAB artifact
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build Android App Bundle (release)
        script: |
          flutter build appbundle --release
      - name: List artifacts
        script: |
          echo "AAB at: build/app/outputs/bundle/release/app-release.aab"
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

        ios_testflight:
    name: MindBreath iOS → TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
      - name: Build IPA (release)
        script: |
          flutter build ipa --release --no-tree-shake-icons
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        integration: asc_mindbreath   # <-- the integration name you’ll create in step 2
        submit_to_testflight: true
        beta_groups:
          - External Testers
