workflows:
  ios_appstore_upload:
    name: iOS → TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - Apple                     # uses APPSTORE_PRIVATE_KEY, APPSTORE_KEY_ID, APPSTORE_ISSUER_ID
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        APP_VERSION: 1.0.0

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Fetch signing files from Apple (cert + App Store profile)
        script: |
          set -e
          # Uses your App Store Connect API key from env vars in group "Apple"
          app-store-connect fetch-signing-files \
            --apiKey "$APPSTORE_PRIVATE_KEY" \
            --issuerId "$APPSTORE_ISSUER_ID" \
            --keyId "$APPSTORE_KEY_ID" \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --create

      - name: Install certs & provisioning profiles
        script: |
          set -e
          # Installs any .p12 placed by the fetch step
          keychain add-certificates
          # Applies the correct provisioning profile(s) to the Xcode project
          xcode-project use-profiles

      - name: Force MANUAL signing on Runner and Pods-Runner (Release)
        script: |
          set -e
          xcode-project automatic-signing disable --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project automatic-signing disable --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"

          xcode-project build-settings set CODE_SIGN_STYLE=Manual --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project build-settings set DEVELOPMENT_TEAM=$TEAM_ID --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project build-settings set PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID --project ios/Runner.xcodeproj --targets "Runner"

          xcode-project build-settings set CODE_SIGN_STYLE=Manual --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"
          xcode-project build-settings set DEVELOPMENT_TEAM=$TEAM_ID --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"

      - name: Create export options (App Store)
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF

      - name: Set marketing version & auto-bump build number
        script: |
          if [ -n "$APP_VERSION" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
          fi
          BUILD_NUM=${CM_BUILD_ID##*-}
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/Runner/Info.plist || true

      - name: Build signed IPA (Release)
        script: flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        # Uses your env vars (group "Apple")
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        api_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true
