workflows:
  ios_appstore_upload:
    name: iOS → TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - Apple                         # pulls APPSTORE_* vars you created in Codemagic UI
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        APP_VERSION: 1.0.0

    # ⬇️ This tells Codemagic to install your uploaded cert/profile
    code_signing:
      certificates:
        - MindBreathDistribution        # <— EXACT name shown in Teams → iOS certificates
      provisioning_profiles:
        - MB_AppStore_Profile           # <— EXACT name shown in Teams → iOS provisioning profiles

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Install certs & profiles from Codemagic
        script: |
          set -e
          keychain add-certificates
          xcode-project use-profiles

      - name: Force MANUAL + Distribution on Runner and Pods-Runner
        script: |
          set -e
          # Disable automatic signing on both projects/targets
          xcode-project automatic-signing disable --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project automatic-signing disable --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"

          # Ensure correct team / bundle id on Runner
          xcode-project build-settings set CODE_SIGN_STYLE=Manual --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project build-settings set DEVELOPMENT_TEAM=$TEAM_ID --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project build-settings set PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID --project ios/Runner.xcodeproj --targets "Runner"

          # Pods-Runner must also be Manual + team
          xcode-project build-settings set CODE_SIGN_STYLE=Manual --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"
          xcode-project build-settings set DEVELOPMENT_TEAM=$TEAM_ID --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner"

          # Point Release configs to your App Store profile and Distribution identity
          xcode-project build-settings set CODE_SIGN_IDENTITY="Apple Distribution" \
            --project ios/Runner.xcodeproj --targets "Runner" --build-config Release
          xcode-project build-settings set PROVISIONING_PROFILE_SPECIFIER="MB_AppStore_Profile" \
            --project ios/Runner.xcodeproj --targets "Runner" --build-config Release

          xcode-project build-settings set CODE_SIGN_IDENTITY="Apple Distribution" \
            --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner" --build-config Release
          xcode-project build-settings set PROVISIONING_PROFILE_SPECIFIER="MB_AppStore_Profile" \
            --project ios/Pods/Pods.xcodeproj --targets "Pods-Runner" --build-config Release

          # Show what we set (for debugging in logs)
          xcode-project build-settings get CODE_SIGN_STYLE --project ios/Runner.xcodeproj --targets "Runner"
          xcode-project build-settings get PROVISIONING_PROFILE_SPECIFIER --project ios/Runner.xcodeproj --targets "Runner" --build-config Release

      - name: Create export options (App Store)
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.carlostechops.mindbreath</key><string>MB_AppStore_Profile</string>
            </dict>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF

      - name: Set marketing version & auto-bump build number
        script: |
          if [ -n "$APP_VERSION" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
          fi
          BUILD_NUM=${CM_BUILD_ID##*-}
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/Runner/Info.plist || true

      - name: Build signed IPA (Release)
        script: flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        # Uses the secrets you added in Codemagic UI (Environment variables, group "Apple")
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        api_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true
