workflows:
  ios_testflight:
    name: iOS → TestFlight
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - Apple                # uses your APPSTORE_PRIVATE_KEY, APPSTORE_KEY_ID, APPSTORE_ISSUER_ID
      vars:
        BUNDLE_ID: com.carlostechops.mindbreath
        TEAM_ID: LRT5QA283X
        APP_VERSION: 1.0.0

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Initialize keychain
        script: keychain initialize

      - name: Fetch signing files (cert + App Store profile)
        script: |
          set -e
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --apiKey "$APPSTORE_PRIVATE_KEY" \
            --issuerId "$APPSTORE_ISSUER_ID" \
            --keyId "$APPSTORE_KEY_ID" \
            --create

      - name: Install certs & provisioning profiles
        script: |
          set -e
          keychain add-certificates
          xcode-project use-profiles      # sets Manual signing + applies the downloaded profile

      - name: Create export options (App Store)
        script: |
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>LRT5QA283X</string>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF

      - name: Set marketing version & auto-bump build number
        script: |
          if [ -n "$APP_VERSION" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" ios/Runner/Info.plist || true
          fi
          BUILD_NUM=${CM_BUILD_ID##*-}
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/Runner/Info.plist || true

      - name: Build signed IPA (Release)
        script: flutter build ipa --release --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        api_key: $APPSTORE_PRIVATE_KEY
        submit_to_testflight: true
