name: mindbreath
description: "MindBreath"
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_launcher_icons: 0.13.1   # pin to the version you actually get

# OLD key that v0.13.x understands:
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/MB-Icon.png
  adaptive_icon_foreground: assets/icon/MB-Icon.png
  adaptive_icon_background: "#0C1413"
  remove_alpha_ios: true
flutter:
  uses-material-design: true

  # If you add images later, list them under assets:
  # assets:
  #   - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
